import type { Theme } from './index'

export const techBlue: Theme = {
  id: 'tech-blue',
  name: '深蓝·技术风',
  accentColor: '#576cbc',
  styles: {
    h1: 'font-size:24px;font-weight:bold;color:#222;border-bottom:3px solid #576cbc;padding-bottom:8px;margin:20px 0 12px;',
    h2: 'font-size:20px;font-weight:bold;color:#222;border-bottom:1px solid #576cbc;padding-bottom:6px;margin:18px 0 10px;',
    h3: 'font-size:17px;font-weight:bold;color:#222;margin:16px 0 8px;',
    p:  'font-size:15px;color:#444;line-height:1.8;margin:10px 0;',
    blockquote: 'border-left:4px solid #576cbc;background:#f0f4ff;padding:10px 16px;margin:12px 0;font-size:14px;color:#555;',
    pre:  'background:#1e1e2e;border-radius:6px;padding:12px 16px;overflow:auto;margin:12px 0;white-space:pre;-moz-tab-size:2;tab-size:2;',
    code: 'font-family:Consolas,Monaco,"Courier New",monospace;font-size:13px;color:#cdd6f4;white-space:pre;',
    strong: 'font-weight:bold;color:#222;',
    em: 'font-style:italic;color:#444;',
    ul: 'padding-left:1.5em;margin:10px 0;list-style-type:disc;',
    ol: 'padding-left:1.5em;margin:10px 0;list-style-type:decimal;',
    li: 'font-size:15px;color:#444;line-height:1.8;margin:4px 0;',
    a:  'color:#576cbc;text-decoration:none;',
    table: 'border-collapse:collapse;width:100%;margin:12px 0;',
    th: 'border:1px solid #c0c8e0;padding:8px;background:#f0f4ff;font-weight:bold;',
    td: 'border:1px solid #c0c8e0;padding:8px;',
    hr: 'border:none;border-top:1px solid #576cbc;margin:20px 0;',
  },
  hljs: {
    'hljs-keyword':  '#89b4fa',
    'hljs-string':   '#a6e3a1',
    'hljs-comment':  '#6c7086',
    'hljs-number':   '#fab387',
    'hljs-title':    '#89dceb',
    'hljs-built_in': '#89b4fa',
    'hljs-type':     '#f5c2e7',
    'hljs-literal':  '#fab387',
    'hljs-attr':     '#cdd6f4',
    'hljs-name':     '#89b4fa',
    'hljs-variable': '#cdd6f4',
    'hljs-tag':      '#89b4fa',
  },
}
