import type { Theme } from './index'

export const warm: Theme = {
  id: 'warm',
  name: '暖色·内容风',
  accentColor: '#a07b50',
  styles: {
    h1: 'font-size:22px;font-weight:bold;color:#333;text-align:center;letter-spacing:2px;margin:20px 0 12px;padding-bottom:8px;border-bottom:1px solid #e8d5b7;',
    h2: 'font-size:18px;font-weight:bold;color:#333;margin:18px 0 10px;padding-bottom:6px;border-bottom:1px solid #e8d5b7;',
    h3: 'font-size:16px;font-weight:bold;color:#555;margin:16px 0 8px;',
    p:  'font-size:15px;color:#555;line-height:2;margin:10px 0;text-indent:2em;',
    blockquote: 'border:none;background:#fef9f0;padding:12px 20px;margin:12px 0;font-size:14px;color:#a07b50;text-align:center;border-radius:4px;',
    pre:  'background:#f9f5ef;border-radius:4px;padding:12px 16px;overflow:auto;margin:12px 0;border:1px solid #e8d5b7;white-space:pre;-moz-tab-size:2;tab-size:2;',
    code: 'font-family:Consolas,Monaco,"Courier New",monospace;font-size:13px;color:#555;white-space:pre;',
    strong: 'font-weight:bold;color:#a07b50;',
    em: 'font-style:italic;color:#a07b50;',
    ul: 'padding-left:1.5em;margin:10px 0;list-style-type:disc;',
    ol: 'padding-left:1.5em;margin:10px 0;list-style-type:decimal;',
    li: 'font-size:15px;color:#555;line-height:2;margin:4px 0;',
    a:  'color:#a07b50;text-decoration:none;',
    table: 'border-collapse:collapse;width:100%;margin:12px 0;',
    th: 'border:1px solid #e8d5b7;padding:8px;background:#fef9f0;font-weight:bold;',
    td: 'border:1px solid #e8d5b7;padding:8px;',
    hr: 'border:none;border-top:1px solid #e8d5b7;margin:20px 0;',
  },
  hljs: {
    'hljs-keyword':  '#a07b50',
    'hljs-string':   '#e6644f',
    'hljs-comment':  '#bbb',
    'hljs-number':   '#6a9fb5',
    'hljs-title':    '#555',
    'hljs-built_in': '#a07b50',
    'hljs-type':     '#a07b50',
    'hljs-literal':  '#e6644f',
    'hljs-attr':     '#555',
    'hljs-name':     '#a07b50',
    'hljs-variable': '#555',
    'hljs-tag':      '#a07b50',
  },
}
